# Generated by Django 6.1.1 on 2026-09-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('setting', models.CharField(max_length=50)),
                ('class_size_avg', models.IntegerField(blank=True, null=True)),
                ('party_score', models.IntegerField(blank=True, default=5, null=True)),
                ('tuition_in_state', models.IntegerField(blank=True, null=True)),
                ('tuition_out_state', models.IntegerField(blank=True, null=True)),
                ('transfer_friendly', models.BooleanField(default=False)),
                ('majors', models.TextField(blank=True, default='')),
                ('residential_rate', models.IntegerField(blank=True, null=True)),
                ('admit_rate', models.FloatField(blank=True, null=True)),
                ('net_price_estimate', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
