"""Seed script for simple sample colleges.
Run with: .venv\Scripts\python.exe scripts\seed_colleges.py
"""
import os
import django
import sys

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.append(BASE_DIR)
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'backend.settings')

django.setup()

from api.models import College

SAMPLES = [
    {
        'name': 'Northwood State',
        'location': 'Northwood, State',
        'setting': 'suburban',
        'class_size_avg': 120,
        'party_score': 4,
        'tuition_in_state': 15000,
        'tuition_out_state': 25000,
        'transfer_friendly': True,
        'majors': 'Computer Science, Engineering, Economics',
        'residential_rate': 70,
        'admit_rate': 0.45,
        'net_price_estimate': 18000,
    },
    {
        'name': 'Evergreen University',
        'location': 'Evergreen City',
        'setting': 'urban',
        'class_size_avg': 90,
        'party_score': 6,
        'tuition_in_state': 20000,
        'tuition_out_state': 30000,
        'transfer_friendly': False,
        'majors': 'Biology, Environmental Science, Computer Science',
        'residential_rate': 60,
        'admit_rate': 0.55,
        'net_price_estimate': 22000,
    },
    {
        'name': 'Hillside College',
        'location': 'Hillside',
        'setting': 'rural',
        'class_size_avg': 200,
        'party_score': 8,
        'tuition_in_state': 12000,
        'tuition_out_state': 22000,
        'transfer_friendly': False,
        'majors': 'Business, Psychology, Education',
        'residential_rate': 40,
        'admit_rate': 0.6,
        'net_price_estimate': 16000,
    },
]

NETHERLANDS = [
    'Rijksuniversiteit Groningen',
    'Universiteit van Amsterdam',
    'Vrije Universiteit Amsterdam',
    'Universiteit Leiden',
    'Universiteit Twente',
    'Universiteit Utrecht',
    'Erasmus University Rotterdam',
    'Technische Universiteit Delft',
    'Wageningen University & Research',
    'Radboud Universiteit Nijmegen',
    'Technische Universiteit Eindhoven',
    'Tilburg University',
    'Maastricht University',
]

for name in NETHERLANDS:
    obj, created = College.objects.get_or_create(name=name, defaults={'location': 'Netherlands'})
    if created:
        print('Created NL', obj.name)
    else:
        print('Exists NL', obj.name)

BELGIUM = [
    "Ghent University",
    "Hasselt University",
    "KU Leuven",
    "University of Antwerp",
    "Vrije Universiteit Brussel",
    "Universite catholique de Louvain",
    "Universite libre de Bruxelles",
    "Universite de Liege",
    "Universite de Mons",
    "Universite de Namur",
]

for name in BELGIUM:
    obj, created = College.objects.get_or_create(name=name, defaults={'location': 'Belgium'})
    if created:
        print('Created BE', obj.name)
    else:
        print('Exists BE', obj.name)

ENGLAND = [
    "Anglia Ruskin University",
    "Arden University",
    "Arts University Bournemouth",
    "Arts University Plymouth",
    "Aston University",
    "BPP University",
    "Bath Spa University",
    "Birkbeck, University of London",
    "Birmingham City University",
    "Bishop Grosseteste University",
    "Bournemouth University",
    "Brunel University London",
    "Buckinghamshire New University",
    "Canterbury Christ Church University",
    "City, University of London",
    "Courtauld Institute of Art",
    "Coventry University",
    "Cranfield University",
    "De Montfort University",
    "Durham University",
    "Edge Hill University",
    "Falmouth University",
    "Goldsmiths, University of London",
    "Harper Adams University",
    "Hartpury University",
    "Health Sciences University",
    "Imperial College London",
    "Institute of Cancer Research",
    "Keele University",
    "King's College London",
    "Kingston University",
    "Lancaster University",
    "Leeds Arts University",
    "Leeds Beckett University",
    "Leeds Trinity University",
    "Liverpool Hope University",
    "Liverpool John Moores University",
    "London Business School",
    "London Institute of Banking & Finance",
    "London Metropolitan University",
    "London School of Economics",
    "London School of Hygiene & Tropical Medicine",
    "London South Bank University",
    "Loughborough University",
    "Manchester Metropolitan University",
    "Middlesex University",
    "Newcastle University",
    "Newman University",
    "Northumbria University",
    "Norwich University of the Arts",
    "Nottingham Trent University",
    "Open University",
    "Oxford Brookes University",
    "Queen Mary University of London",
    "Ravensbourne University London",
    "Regent's University London",
    "Roehampton University",
    "Royal Academy of Music",
    "Royal Agricultural University",
    "Royal Central School of Speech and Drama",
    "Royal Holloway, University of London",
    "Royal Veterinary College",
    "School of Oriental and African Studies",
    "Sheffield Hallam University",
    "Southampton Solent University",
    "St George's, University of London",
    "St Mary's University Twickenham",
    "Staffordshire University",
    "Teesside University",
    "University College Birmingham",
    "University College London",
    "University College of Estate Management",
    "University College of Osteopathy",
    "University for the Creative Arts",
    "University of Bath",
    "University of Bedfordshire",
    "University of Birmingham",
    "University of Bradford",
    "University of Brighton",
    "University of Bristol",
    "University of Buckingham",
    "University of Cambridge",
    "University of Central Lancashire",
    "University of Chester",
    "University of Chichester",
    "University of Cumbria",
    "University of Derby",
    "University of East Anglia",
    "University of East London",
    "University of Essex",
    "University of Exeter",
    "University of Gloucestershire",
    "University of Greater Manchester",
    "University of Greenwich",
    "University of Hertfordshire",
    "University of Huddersfield",
    "University of Hull",
    "University of Kent",
    "University of Law",
    "University of Leeds",
    "University of Leicester",
    "University of Lincoln",
    "University of Liverpool",
    "University of London",
    "University of Manchester",
    "University of Northampton",
    "University of Nottingham",
    "University of Oxford",
    "University of Plymouth",
    "University of Portsmouth",
    "University of Reading",
    "University of Salford",
    "University of Sheffield",
    "University of Southampton",
    "University of St Mark & St John",
    "University of Suffolk",
    "University of Sunderland",
    "University of Surrey",
    "University of Sussex",
    "University of Warwick",
    "University of West London",
    "University of Westminster",
    "University of Winchester",
    "University of Wolverhampton",
    "University of Worcester",
    "University of York",
    "University of the Arts London",
    "University of the West of England",
    "Writtle University College",
    "York St John University",
]

for name in ENGLAND:
    obj, created = College.objects.get_or_create(name=name, defaults={'location': 'England'})
    if created:
        print('Created EN', obj.name)
    else:
        print('Exists EN', obj.name)

FRANCE = [
    "Aix-Marseille University",
    "Avignon University",
    "Bordeaux Montaigne University",
    "CY Cergy Paris University",
    "Claude Bernard University Lyon 1",
    "Clermont Auvergne University",
    "Gustave Eiffel University",
    "Jean Monnet University Saint-Etienne",
    "Jean Moulin University Lyon 3",
    "La Rochelle University",
    "Le Havre Normandy University",
    "Le Mans University",
    "Lumiere University Lyon 2",
    "Marie and Louis Pasteur University",
    "Nantes Universite",
    "Paris 1 Pantheon-Sorbonne University",
    "Paris 8 University Vincennes-Saint-Denis",
    "Paris Cite University",
    "Paris Nanterre University",
    "Paris-East Creteil University",
    "Paris-Pantheon-Assas University",
    "Paris-Saclay University",
    "Polytechnic University of Hauts-de-France",
    "Rennes 2 University",
    "Sorbonne Nouvelle University Paris 3",
    "Sorbonne Paris North University",
    "Sorbonne University",
    "Southern Brittany University",
    "Toulouse Capitole University",
    "Universite Savoie Mont Blanc",
    "University Pasquale Paoli (Corsica)",
    "University of Angers",
    "University of Artois",
    "University of Bordeaux",
    "University of Burgundy Europe",
    "University of Caen Normandy",
    "University of Evry Val d'Essonne",
    "University of French Guiana",
    "University of French Polynesia",
    "University of Lille",
    "University of Limoges",
    "University of Mayotte",
    "University of Montpellier",
    "University of Montpellier Paul-Valery",
    "University of New Caledonia",
    "University of Nimes",
    "University of Orleans",
    "University of Pau and the Adour Region",
    "University of Perpignan Via Domitia",
    "University of Picardy Jules Verne",
    "University of Poitiers",
    "University of Reims Champagne-Ardenne",
    "University of Rennes",
    "University of Reunion Island",
    "University of Rouen Normandy",
    "University of Strasbourg",
    "University of Toulon",
    "University of Toulouse",
    "University of Toulouse-Jean Jaures",
    "University of Tours",
    "University of Upper Alsace",
    "University of Versailles Saint-Quentin-en-Yvelines",
    "University of Western Brittany",
    "University of the French Antilles",
    "University of the Littoral Opal Coast",
]

for name in FRANCE:
    obj, created = College.objects.get_or_create(name=name, defaults={'location': 'France'})
    if created:
        print('Created FR', obj.name)
    else:
        print('Exists FR', obj.name)

GERMANY = [
    "Augsburg University",
    "Augustana Divinity School Neuendettelsau",
    "Bard College Berlin",
    "Bauhaus-University Weimar",
    "Berlin University of Psychology",
    "Berlin University of the Arts",
    "Bielefeld University",
    "Brandenburg Medical School Theodor Fontane",
    "Brandenburg University of Technology Cottbus-Senftenberg",
    "Bucerius Law School",
    "Catholic University of Eichstatt-Ingolstadt",
    "Center for Jewish Studies Heidelberg",
    "Charite - Universitatsmedizin Berlin",
    "Charlotte Fresenius University",
    "Cologne University of Catholic Theology",
    "Constructor University",
    "Dresden International University",
    "EBS University for Business and Law",
    "ESCP Business School (Berlin campus)",
    "European School of Management and Technology",
    "European University Viadrina",
    "Frankfurt School of Finance & Management",
    "Free University of Berlin",
    "Freiberg University of Mining and Technology",
    "Freiburg University of Education",
    "German International University",
    "German Sport University Cologne",
    "German University of Administrative Sciences Speyer",
    "Goethe University Frankfurt",
    "HHL Leipzig Graduate School of Management",
    "HafenCity University Hamburg",
    "Hannover Medical School",
    "Heinrich Heine University Dusseldorf",
    "Helmut Schmidt University",
    "Hertie School",
    "Humboldt University of Berlin",
    "International Psychoanalytic University Berlin",
    "Karlsruhe Institute of Technology",
    "Karlsruhe University of Education",
    "Kiel University",
    "Kuhne Logistics University",
    "LMU Munich",
    "Leibniz University Hannover",
    "Leipzig University",
    "Leuphana University of Luneburg",
    "Ludwigsburg University of Education",
    "Martin Luther University of Halle-Wittenberg",
    "Medical University of Lausitz",
    "Munich School of Philosophy",
    "Munster University of Philosophy and Theology",
    "Oberursel Theological University",
    "Otto von Guericke University of Magdeburg",
    "Paderborn Faculty of Theology",
    "RPTU University Kaiserslautern-Landau",
    "RWTH Aachen University",
    "Ruhr University Bochum",
    "Saarland University",
    "Sankt Georgen Graduate School of Philosophy and Theology",
    "Stuttgart Free University",
    "TU Berlin",
    "TU Braunschweig",
    "TU Chemnitz",
    "TU Clausthal",
    "TU Darmstadt",
    "TU Dortmund",
    "TU Dresden",
    "TU Hamburg",
    "TU Ilmenau",
    "TU Munich",
    "Theological University Wuppertal",
    "Theological University of Friedensau",
    "Trier Faculty of Theology",
    "University of Bamberg",
    "University of Bayreuth",
    "University of Bonn",
    "University of Bremen",
    "University of Cologne",
    "University of Duisburg-Essen",
    "University of Education Schwabisch Gmund",
    "University of Erfurt",
    "University of Erlangen-Nurnberg",
    "University of Flensburg",
    "University of Freiburg",
    "University of Giessen",
    "University of Gottingen",
    "University of Greifswald",
    "University of Hagen",
    "University of Hamburg",
    "University of Heidelberg",
    "University of Hildesheim",
    "University of Hohenheim",
    "University of Jena",
    "University of Kassel",
    "University of Koblenz",
    "University of Konstanz",
    "University of Lubeck",
    "University of Mainz",
    "University of Mannheim",
    "University of Marburg",
    "University of Munster",
    "University of Oldenburg",
    "University of Osnabruck",
    "University of Paderborn",
    "University of Passau",
    "University of Potsdam",
    "University of Regensburg",
    "University of Rostock",
    "University of Siegen",
    "University of Stuttgart",
    "University of Technology Nuremberg",
    "University of Theology Fulda",
    "University of Trier",
    "University of Tubingen",
    "University of Ulm",
    "University of Vechta",
    "University of Veterinary Medicine Hannover",
    "University of Wuppertal",
    "University of Wurzburg",
    "University of the Bundeswehr Munich",
    "Vinzenz Pallotti University",
    "WHU - Otto Beisheim School of Management",
    "Weingarten University of Education",
    "Witten/Herdecke University",
    "Zeppelin University",
]

for name in GERMANY:
    obj, created = College.objects.get_or_create(name=name, defaults={'location': 'Germany'})
    if created:
        print('Created DE', obj.name)
    else:
        print('Exists DE', obj.name)

ITALY = [
    "Basilicata University",
    "Biomedical University of Rome (Campus Bio-Medico)",
    "Bocconi University",
    "Ca' Foscari University of Venice",
    "D'Annunzio University of Chieti-Pescara",
    "ESCP Europe Turin Campus",
    "European University of Rome",
    "Faenza ISIA",
    "Florence ISIA",
    "Foreigners University of Siena",
    "Foro Italico University of Rome",
    "Free University of Bozen-Bolzano",
    "Giustino Fortunato University",
    "Guglielmo Marconi University",
    "Humanitas University",
    "IMT School for Advanced Studies Lucca",
    "IULM University of Milan",
    "Institute for Advanced Study of Pavia (IUSS)",
    "International School for Advanced Studies (SISSA)",
    "International University College of Turin",
    "Italian Institute of Human Sciences (SUM)",
    "Italian University Line (IUL)",
    "Iuav University of Venice",
    "Kore University of Enna",
    "LUISS University of Rome",
    "LUMSA University",
    "Libera Universita Mediterranea (LUM)",
    "Link Campus University",
    "Magna Graecia University of Catanzaro",
    "Marche Polytechnic University",
    "Mercatorum University",
    "Niccolo Cusano University",
    "Parthenope University of Naples",
    "Pegaso University of Naples",
    "Politecnico di Torino",
    "Polytechnic University of Bari",
    "Polytechnic University of Milan",
    "Rome ISIA",
    "Salesian University Institute of Venice (IUSVE)",
    "San Raffaele University of Rome (telematic)",
    "Sant'Anna School of Advanced Studies",
    "Sapienza University of Rome",
    "Scuola Normale Superiore",
    "Suor Orsola Benincasa University of Naples",
    "Tuscia University",
    "UniCamillus University",
    "UniNettuno University",
    "Unitelma Sapienza University",
    "Universita Cattolica del Sacro Cuore",
    "University Carlo Cattaneo (LIUC)",
    "University Leonardo da Vinci",
    "University for Foreigners Dante Alighieri Reggio Calabria",
    "University for Foreigners Perugia",
    "University of Aosta Valley",
    "University of Bari",
    "University of Bergamo",
    "University of Bologna",
    "University of Brescia",
    "University of Cagliari",
    "University of Calabria",
    "University of Camerino",
    "University of Campania Luigi Vanvitelli",
    "University of Cassino",
    "University of Catania",
    "University of Eastern Piedmont",
    "University of Ferrara",
    "University of Florence",
    "University of Foggia",
    "University of Gastronomic Sciences",
    "University of Genoa",
    "University of Insubria",
    "University of International Studies of Rome (UNINT)",
    "University of L'Aquila",
    "University of Macerata",
    "University of Messina",
    "University of Milan",
    "University of Milan-Bicocca",
    "University of Modena and Reggio Emilia",
    "University of Molise",
    "University of Naples Federico II",
    "University of Naples L'Orientale",
    "University of Padua",
    "University of Palermo",
    "University of Parma",
    "University of Pavia",
    "University of Perugia",
    "University of Pisa",
    "University of Reggio Calabria (Mediterranea)",
    "University of Rome III (Roma Tre)",
    "University of Rome Tor Vergata",
    "University of Salento",
    "University of Salerno",
    "University of Sannio",
    "University of Sassari",
    "University of Siena",
    "University of Teramo",
    "University of Trento",
    "University of Trieste",
    "University of Turin",
    "University of Udine",
    "University of Urbino",
    "University of Verona",
    "Urbino ISIA",
    "Vita-Salute San Raffaele University",
    "e-Campus University",
]

for name in ITALY:
    obj, created = College.objects.get_or_create(name=name, defaults={'location': 'Italy'})
    if created:
        print('Created IT', obj.name)
    else:
        print('Exists IT', obj.name)

SPAIN = [
    "Abat Oliba CEU University",
    "Al-Andalusia Islamic University of Spain",
    "Alfonso X University",
    "Atlantic-Mediterranean Technological University",
    "Autonomous University of Barcelona",
    "Autonomous University of Madrid",
    "CEU San Pablo University",
    "CUNEF University",
    "Camilo Jose Cela University",
    "Carlos III University of Madrid",
    "Catholic University of Avila",
    "Comillas Pontifical University",
    "Complutense University of Madrid",
    "ESIC University",
    "European University (Barcelona)",
    "European University Gasteiz",
    "European University of Canarias",
    "European University of Madrid",
    "European University of the Atlantic",
    "Fernando III University",
    "Fernando Pessoa Canarias University",
    "Francisco de Vitoria University",
    "Harbour.Space University",
    "IE University",
    "Intercontinental University of Business",
    "International University of Andalusia",
    "International University of Catalonia",
    "International University of La Rioja",
    "Jaume I University",
    "King Juan Carlos University",
    "Les Roches Marbella International School of Hotel Management",
    "Loyola University Andalusia",
    "Menendez Pelayo International University",
    "Miguel Hernandez University of Elche",
    "Miguel de Cervantes European University",
    "Mondragon University",
    "National University of Distance Education (UNED)",
    "Nebrija University",
    "Open University of Catalonia",
    "Pablo de Olavide University",
    "Polytechnic University of Cartagena",
    "Polytechnic University of Catalonia",
    "Polytechnic University of Valencia",
    "Pompeu Fabra University",
    "Pontifical University of Salamanca",
    "Public University of Navarre",
    "Ramon Llull University",
    "Rovira i Virgili University",
    "San Antonio Catholic University of Murcia",
    "San Damaso Ecclesiastical University",
    "San Jorge University",
    "Schellhammer Business School",
    "Technical University of Madrid",
    "Universidad CEU Cardenal Herrera",
    "Universidad a Distancia de Madrid",
    "University Isabel I",
    "University of A Coruna",
    "University of Alcala",
    "University of Alicante",
    "University of Almeria",
    "University of Barcelona",
    "University of Burgos",
    "University of Cadiz",
    "University of Cantabria",
    "University of Castilla-La Mancha",
    "University of Cordoba",
    "University of Design, Innovation, and Technology",
    "University of Deusto",
    "University of Extremadura",
    "University of Girona",
    "University of Granada",
    "University of Huelva",
    "University of Jaen",
    "University of La Laguna",
    "University of La Rioja",
    "University of Las Palmas de Gran Canaria",
    "University of Leon",
    "University of Lleida",
    "University of Malaga",
    "University of Murcia",
    "University of Navarre",
    "University of Oviedo",
    "University of Salamanca",
    "University of Santiago de Compostela",
    "University of Seville",
    "University of Valencia",
    "University of Valladolid",
    "University of Vic",
    "University of Vigo",
    "University of Zaragoza",
    "University of the Balearic Islands",
    "University of the Basque Country",
    "University of the Conservation (Catalonia)",
    "University of the Middle Atlantic",
    "Valencia Catholic University Saint Vincent Martyr",
    "Valencian International University",
]

for name in SPAIN:
    obj, created = College.objects.get_or_create(name=name, defaults={'location': 'Spain'})
    if created:
        print('Created ES', obj.name)
    else:
        print('Exists ES', obj.name)

AUSTRALIA = [
    "Adelaide University",
    "Australian Catholic University",
    "Australian College of Theology",
    "Australian National University",
    "Australian University of Theology",
    "Avondale University",
    "Bond University",
    "CQUniversity",
    "Charles Darwin University",
    "Charles Sturt University",
    "Curtin University",
    "Deakin University",
    "Edith Cowan University",
    "Federation University Australia",
    "Flinders University",
    "Griffith University",
    "James Cook University",
    "La Trobe University",
    "Macquarie University",
    "Monash University",
    "Murdoch University",
    "Queensland University of Technology",
    "RMIT University",
    "Southern Cross University",
    "Swinburne University of Technology",
    "Torrens University Australia",
    "University of Canberra",
    "University of Divinity",
    "University of Melbourne",
    "University of New England",
    "University of New South Wales",
    "University of Newcastle",
    "University of Notre Dame Australia",
    "University of Queensland",
    "University of Southern Queensland",
    "University of Sydney",
    "University of Tasmania",
    "University of Technology Sydney",
    "University of Western Australia",
    "University of Wollongong",
    "University of the Sunshine Coast",
    "Victoria University",
    "Western Sydney University",
]

for name in AUSTRALIA:
    obj, created = College.objects.get_or_create(name=name, defaults={'location': 'Australia'})
    if created:
        print('Created AU', obj.name)
    else:
        print('Exists AU', obj.name)

UNITED_STATES = [
    "Assumption University",
    "Bay Path University",
    "Bentley University",
    "Boston University",
    "Brandeis University",
    "Bridgewater State University",
    "Clark University",
    "Fitchburg State University",
    "Framingham State University",
    "Harvard University",
    "Lasell University",
    "Lesley University",
    "Northeastern University",
    "Salem State University",
    "Simmons University",
    "Suffolk University",
    "Tufts University",
    "University of Massachusetts Amherst",
    "University of Massachusetts Boston",
    "University of Massachusetts Chan Medical School",
    "University of Massachusetts Dartmouth",
    "University of Massachusetts Lowell",
    "Western New England University",
    "Westfield State University",
    "Worcester State University",
    "Adelphi University",
    "Alfred University",
    "Binghamton University (SUNY)",
    "Buffalo State University (SUNY)",
    "Clarkson University",
    "Colgate University",
    "Columbia University",
    "Cornell University",
    "D'Youville University",
    "Daemen University",
    "DeVry University (NY)",
    "Empire State University (SUNY)",
    "Excelsior University",
    "Fordham University",
    "Hofstra University",
    "Houghton University",
    "Long Island University",
    "Manhattanville University",
    "Marist University",
    "Medaille University",
    "Mercy University",
    "Molloy University",
    "Monroe University",
    "Nazareth University",
    "New York University",
    "Niagara University",
    "Pace University",
    "Roberts Wesleyan University",
    "Rockefeller University",
    "SUNY Downstate Health Sciences University",
    "SUNY Upstate Medical University",
    "St. Bonaventure University",
    "St. John Fisher University",
    "St. John's University",
    "St. Joseph's University (New York)",
    "St. Lawrence University",
    "Stony Brook University (SUNY)",
    "Syracuse University",
    "Touro University",
    "University at Albany (SUNY)",
    "University at Buffalo (SUNY)",
    "University of Rochester",
    "Utica University",
    "Yeshiva University",
    "Alhambra Medical University",
    "Alliant International University",
    "American Heritage University of Southern California",
    "American Jewish University",
    "American Management University",
    "American University of Health Sciences",
    "Anaheim University",
    "Antioch University Los Angeles",
    "Antioch University Santa Barbara",
    "Azusa Pacific University",
    "Bethesda University",
    "Biola University",
    "California Aeronautical University",
    "California Baptist University",
    "California Health Sciences University",
    "California InterContinental University",
    "California Lutheran University",
    "California Metropolitan University",
    "California Miramar University",
    "California Northstate University College of Medicine",
    "California Polytechnic State University, San Luis Obispo",
    "California South Bay University",
    "California Southern University",
    "California State Polytechnic University, Humboldt",
    "California State Polytechnic University, Pomona",
    "California State University Channel Islands",
    "California State University San Marcos",
    "California State University, Bakersfield",
    "California State University, Chico",
    "California State University, Dominguez Hills",
    "California State University, East Bay",
    "California State University, Fresno",
    "California State University, Fullerton",
    "California State University, Long Beach",
    "California State University, Los Angeles",
    "California State University, Monterey Bay",
    "California State University, Moss Landing Marine Laboratories",
    "California State University, Northridge",
    "California State University, Sacramento",
    "California State University, San Bernardino",
    "California State University, Stanislaus",
    "California University of Management and Sciences",
    "California University of Science and Medicine",
    "Chapman University",
    "Charles R. Drew University of Medicine and Science",
    "Claremont Graduate University",
    "Claremont Lincoln University",
    "Concordia University Irvine",
    "Daybreak University",
    "DeVry University (Ontario, CA)",
    "Dharma Realm Buddhist University",
    "Dominican University of California",
    "Dongguk University",
    "Fielding Graduate University",
    "Five Branches University",
    "Fremont University",
    "Fresno Pacific University",
    "Golden Gate University",
    "Haven University",
    "Hope International University",
    "Humphreys University",
    "International Technological University",
    "John Paul the Great Catholic University",
    "La Sierra University",
    "Life Pacific University",
    "Lincoln University (Oakland)",
    "Loma Linda University",
    "Los Angeles Pacific University",
    "Loyola Marymount University",
    "Marshall B. Ketchum University",
    "Meridian University",
    "Minerva University",
    "Mount St. Mary's University",
    "National University",
    "Notre Dame de Namur University",
    "Palo Alto University",
    "Pepperdine University",
    "Point Loma Nazarene University",
    "Reach University",
    "Saint Mary's College of California",
    "San Diego State University",
    "San Diego University for Integrative Studies",
    "San Francisco Bay University",
    "San Francisco State University",
    "San Jose State University",
    "Santa Clara University",
    "Saybrook University",
    "Simpson University",
    "Sofia University",
    "Soka University of America",
    "Sonoma State University",
    "South Baylo University",
    "Southern California University of Health Sciences",
    "Southern States University",
    "St. John's University (California)",
    "Stanbridge University",
    "Stanford University",
    "Touro University California",
    "Touro University Worldwide",
    "Trident University International",
    "United States University",
    "University of California College of the Law, San Francisco",
    "University of California, Berkeley",
    "University of California, Davis",
    "University of California, Irvine",
    "University of California, Los Angeles",
    "University of California, Merced",
    "University of California, Riverside",
    "University of California, San Diego",
    "University of California, San Francisco",
    "University of California, Santa Barbara",
    "University of California, Santa Cruz",
    "University of East-West Medicine",
    "University of La Verne",
    "University of Massachusetts Global",
    "University of Redlands",
    "University of San Diego",
    "University of San Francisco",
    "University of Silicon Andhra",
    "University of Silicon Valley",
    "University of Southern California",
    "University of St. Augustine for Health Sciences",
    "University of West Los Angeles",
    "University of the Pacific",
    "University of the People",
    "University of the West",
    "Vanguard University",
    "West Coast University",
    "Westcliff University",
    "Western University of Health Sciences",
    "William Jessup University",
    "Woodbury University",
    "World Mission University",
    "Yo San University of Traditional Chinese Medicine",
    "AdventHealth University",
    "Albizu University",
    "Atlantis University",
    "Ave Maria University",
    "Barry University",
    "Bethune-Cookman University",
    "DeVry University (Orlando, FL)",
    "Edward Waters University",
    "Embry-Riddle Aeronautical University",
    "Everglades University",
    "Florida A&M University",
    "Florida Atlantic University",
    "Florida Gulf Coast University",
    "Florida International University",
    "Florida Memorial University",
    "Florida National University",
    "Florida Polytechnic University",
    "Florida State University",
    "Full Sail University",
    "Herzing University",
    "Jacksonville University",
    "Keiser University",
    "Lynn University",
    "Miami Regional University",
    "National Louis University",
    "Nova Southeastern University",
    "Palm Beach Atlantic University",
    "Rasmussen University",
    "Saint Leo University",
    "Schiller International University",
    "Southeastern University (Florida)",
    "St. Thomas University (Florida)",
    "Talmudic University Yeshiva Bais Moshe Chaim",
    "University of Central Florida",
    "University of Florida",
    "University of Fort Lauderdale",
    "University of Miami",
    "University of North Florida",
    "University of South Florida",
    "University of St. Augustine for Health Sciences (FL)",
    "University of Tampa",
    "University of West Florida",
    "Warner University",
    "Webber International University",
    "Western Michigan University Cooley Law School",
]

for name in UNITED_STATES:
    obj, created = College.objects.get_or_create(name=name, defaults={'location': 'United States'})
    if created:
        print('Created US', obj.name)
    else:
        print('Exists US', obj.name)

for s in SAMPLES:
    obj, created = College.objects.get_or_create(name=s['name'], defaults=s)
    if created:
        print('Created', obj.name)
    else:
        print('Exists', obj.name)

print('Done')
